SwanseaUniversityMedical/workflows-test

.github/workflows/Whalesay.yaml, .github/workflows/Whalesay2.yaml
=> Test: test break whalesay2 again

.github/pull_request_template.md
=> style: adjust pr template

.github/pull_request_template.md, .github/workflows/commitlint.yaml
=> style: fix pr template

.github/workflows/controller-container.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/133 to see if caching works correctly and if the final release containers are noticeably different from the inline cache rc containers.
=> feat(controller-container): test container workflow release cache

.github/workflows/controller-container.yaml
Bump container workflow to 1.6.0 after successful test of https://github.com/SwanseaUniversityMedical/workflows/pull/133
=> feat(controller-container): bump ci to 1.6.0

.github/workflows/controller-container.yaml
Test automatic merge of release commits into the trunk branch.
=> feat(controller-container): test release merge

containers/controller/src/controller.py
=> feat(controller-container): test release merge (#77)

.github/workflows/controller-container.yaml
Grant release ci pr write permission.
=> fix(controller-container): give pr write permission

.github/workflows/controller-container.yaml, containers/controller/src/controller.py
Apply new pr write permission.
=> fix(controller-container): give pr write permission (#79)

.github/workflows/controller-container.yaml
Revert testing automatic merge PRs.
=> feat(controller-container): revert merge pr test

.github/labeler.yaml, .github/workflows/controller-container.yaml, .github/workflows/fizzbuzz-chart.yaml, .github/workflows/fizzbuzz-crds-chart.yaml
Adjust naming of maintenance branches.
=> feat: adjust maintenance branch names

containers/controller/src/controller.py
Trigger a release so we can test a maintenance branch.
=> feat: trigger a release

containers/controller/src/controller.py
Test making a maintenance branch release.
=> fix(controller-container): test a maintenance branch fix

.github/workflows/controller-container.yaml, containers/controller/src/controller.py
Fix the maintenance release branch in the ci.
=> fix(controller-container): fix the maintenance release branch in the ci

.github/commitlint.config.mjs, .github/workflows/pr-title-commitlint.yaml, containers/controller/src/controller.py
=> test(controller-container): Update controller.py

.github/workflows/pr-title-commitlint.yaml
=> chore(deps): Update pr-title-commitlint.yaml

containers/controller/src/controller.py
=> feat(controller-container): Update controller.py

.github/workflows/controller-container.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/145 
=> feat(controller-container): test step summary output

charts/fizzbuzz-crds/Chart.yaml, charts/fizzbuzz/Chart.yaml
=> test: mangle charts

charts/fizzbuzz-crds/Chart.yaml, charts/fizzbuzz/Chart.yaml
=> feat: one mangled chart

charts/fizzbuzz/values.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/150 on a failed release.
=> feat(fizzbuzz-chart): Update values.yaml to trigger failed release

charts/fizzbuzz-crds/Chart.yaml, charts/fizzbuzz/Chart.yaml
=> fix: fix the mangled charts and update to new workflows version

.github/workflows/fizzbuzz-chart.yaml, .github/workflows/fizzbuzz-crds-chart.yaml
Update charts workflow post release testing.
=> chore(deps): Update charts workflow

.github/workflows/controller-container.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/152
=> feat(controller-container): test optimized containers workflow

.github/workflows/controller-container.yaml
Post https://github.com/SwanseaUniversityMedical/workflows/pull/152
=> chore(controller-container): bump workflow version

.github/commitlint.config.mjs, .github/labeler.yaml, .github/workflows/fizzbuzz-chart.yaml, .github/workflows/fizzbuzz-crds-chart.yaml, .github/workflows/trino-container.yaml, containers/trino/Dockerfile
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/153
=> feat(trino-container): add trino container to test extra tag command

.github/workflows/trino-container.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/153
=> fix(trino-container): Update trino-container.yaml extra tag command new line

.github/workflows/trino-container.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/153.
=> fix(trino-container): Update trino-container.yaml command captured multiple lines

.github/workflows/controller-container.yaml, .github/workflows/trino-container.yaml
=> chore(deps): Update trino-container.yaml workflow

.github/pull_request_template.md, .github/workflows/controller-container.yaml, .github/workflows/fizzbuzz-chart.yaml, .github/workflows/fizzbuzz-crds-chart.yaml, .github/workflows/trino-container.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/156
=> feat: test intuit auto

.github/workflows/controller-container.yaml, .github/workflows/controller-flake8.yaml, .github/workflows/fizzbuzz-chart.yaml, .github/workflows/fizzbuzz-crds-chart.yaml, .github/workflows/pr-title-commitlint.yaml, .github/workflows/trino-container.yaml, charts/fizzbuzz-crds/values.yaml, containers/trino/Dockerfile
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/156
=> feat: make concurrency cancel field conditional on github event

charts/fizzbuzz-crds/values.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/156
=> feat: trigger a release to test re-running a previous release skips

.github/workflows/controller-container.yaml, .github/workflows/fizzbuzz-chart.yaml, .github/workflows/fizzbuzz-crds-chart.yaml, .github/workflows/pr-labeler.yaml, .github/workflows/pr-title-commitlint.yaml, .github/workflows/trino-container.yaml
Pins versions after testing https://github.com/SwanseaUniversityMedical/workflows/pull/156
=> chore(deps): pin workflows to release after testing

.github/workflows/pr-title-commitlint.yaml
Bumps to include https://github.com/SwanseaUniversityMedical/workflows/pull/157
=> chore(deps): bump commitlint workflow

.github/workflows/renovate.yaml
Use a fine-grained access token to run renovate.
=> fix: use finegrained access token

.github/CODEOWNERS
=> feat: create CODEOWNERS file

.github/workflows/renovate.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/169
=> fix: renovate harbor user var

.github/workflows/renovate.yaml
Pin after testing https://github.com/SwanseaUniversityMedical/workflows/pull/169
=> chore(deps): pin renovate after testing

.github/workflows/multi-container-test.yaml
=> feat: force a new release

.github/workflows/multi-container-test.yaml
=> feat: bulk chart release

.github/workflows/multi-container-test.yaml
=> refactor: update workflow to remove unused inputs

.github/workflows/multi-container-test.yaml
=> refactor: change job name

.github/workflows/multi-container-test.yaml, containers/controller/Dockerfile
=> test: check failure with bad tests and bad dockerfiles

.github/workflows/multi-container-test.yaml, containers/controller/Dockerfile
=> refactor: fix dockerfile and use new tags

.github/workflows/multi-container-test.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/184
=> test: bulk container release

.github/workflows/multi-container-test.yaml
Reverts SwanseaUniversityMedical/workflows-test#172
=> Revert "test: bulk container release"

.github/workflows/multi-container-test.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/186
=> test: bulk comment fix

.github/renovate.js
=> refactor: enable dry run

.github/renovate.js
=> feat: add new rules

.github/workflows/azurekeycloaktester-container.yaml, .github/workflows/azurekeycloaktester-sonar.yaml
=> fix: run sonar on release tags not on push to main

.github/workflows/azurekeycloaktester-container.yaml, .github/workflows/azurekeycloaktester-sonar.yaml
=> chore: pin sonar workflow

.github/workflows/azurekeycloaktester-sonar.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/203
=> test: sonar container pin

.github/workflows/multi-container-test.yaml
=> test: trigger bulk container release

.github/workflows/internal-container.yaml
=> test: trigger single container release

.github/renovate.js
=> ci: adjust renovate schedule for bumping workflows

.github/workflows/azurekeycloaktester-sonar.yaml
=> fix: update sonar token

.github/workflows/azurekeycloaktester-container.yaml, .github/workflows/bulk-chart.yaml, .github/workflows/bulk-container.yaml, .github/workflows/controller-container.yaml, .github/workflows/fizzbuzz-chart.yaml, .github/workflows/fizzbuzz-crds-chart.yaml, .github/workflows/trino-container.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/262.
=> test: release skip labels

.github/workflows/azurekeycloaktester-container.yaml, .github/workflows/bulk-chart.yaml, .github/workflows/bulk-container.yaml, .github/workflows/controller-container.yaml, .github/workflows/fizzbuzz-chart.yaml, .github/workflows/fizzbuzz-crds-chart.yaml, .github/workflows/trino-container.yaml
Reverts SwanseaUniversityMedical/workflows-test#227
=> Revert "test: release skip labels"

renovate.json
Enable dedicated renovate to process this repo.
=> ci: enable dedicated renovate

.github/CODEOWNERS
=> fix: CODEOWNERS formatting

.github/workflows/bulk-container.yaml, .github/workflows/controller-container.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/290
=> test: controller-container.yaml

.github/workflows/bulk-container.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/290
=> test: bulk-container.yaml

.github/workflows/test-asset.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/314 🥧.
=> test: tag based release pipeline

.github/workflows/test-asset.yaml
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/314.
=> ci: trigger test-asset.yaml

.github/workflows/test-asset.yaml
Test https://github.com/SwanseaUniversityMedical/workflows/pull/314
=> ci: trigger

.github/workflows/azurekeycloaktester-sonar.yaml, containers/AzureKeycloakTester/AzureKeycloakTester.csproj, containers/AzureKeycloakTester/Dockerfile
Tests https://github.com/SwanseaUniversityMedical/workflows/pull/315
=> test: sonar
